version: '3.11'

services:

  nginx:
    container_name: nginx
    networks:
      - inception
    build: ./requirements/nginx
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: /home/msharifi/data/mysql
  wordpress:
    driver: local
    driver_opts:
        type: volumes
        o: bind
        device: /home/msharifi/data/wordpress

networks:
  inception:
      driver: bridge
